language: java
script: "./buildViaTravis.sh"
deploy:
  provider: releases
  api_key:
    secure: j1113mTxzTXmSHth9G/wYy6Wa1tLwMzS0fIsCDV0UeYhtE+ApKYp0ZHHoy/KIpJ1lxoAvnEjVuOJXUPbEnSigkb9j7qqNzuS0+go0h5RzrFmr/7dRCWoenxmzJhdFMXLbdUuR84YGYjaVIgxa2CZY+qUjaZPGYvmIMycVLSX3NiEjCWykCFvQ5bGsQRbXilShBmSV6TGnvEOCuexWe2HaON00FYCYPmjYh7PYNR7MO7OsQNHCSvnSMFMIx8HmEfnljHUP2Ki5xf1Tp8/YXLBgkCaLmGUGcruuYe5XeEgTdkz3voqzqe6j1ks4BNKut/QPwgJ8t2EnP5C+sMqcDgeOmlSA9R3daB9i/Lu94aCmHuMYOxzY0kL48q0FTiuYVeOoDGAbezPnHq6wrbI4e2EHZE1Xa9NgtX3Ay+IgeUeYtoVTSn45C5uL9Gw78aojGt+IgvCg8pPT/p2HyUi1RVNikZKD/JY2nWg5KCet3p/7ICgEPSDWL2pwicq8EIWqlAm/uoBy3+IbpZb6rTIn1LtY0SRYu1dQ7tzSoWu3954NPgxtDvF2vgNu/Nreqxzsq/WL9Rqi7nHs6NAeepxpU2E/hiQk+LJwFI85j6fgB3GB7Vu7TASHX9E8LLTetKNbKbRg8meaaCwKDRklFP5BEx7dDGV81VwMgCzY4f17T49q34=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  edge: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-helm-plugin
